swagger: '2.0'
info:
  version: 0.0.1
  title: Kartozoa
  description: Simple Kartotherian Tile Server Remix
  contact:
    name: Lucas Leblow
    email: leblowl@gmail.com
  license:
    name: Apache2
    url: http://www.apache.org/licenses/LICENSE-2.0
paths:
  # from routes/root.js
  /robots.txt:
    get:
      tags:
        - Root
        - Robots
      description: Gets robots.txt
      x-amples:
        - title: robots.txt check
          request: {}
          response:
            status: 200
            headers:
              user-agent: '*'
              disallow: '/'
  /:
    get:
      tags:
        - Root
      description: The root service end-point
      produces:
        - application/json
      x-amples:
        - title: root with no query params
          request: {}
          response:
            status: 404
        - title: spec from root
          request:
            query:
              spec: true
          response:
            status: 200
        - title: root with wrong query param
          request:
            query:
              fooo: true
          response:
            status: 404
 
  # from routes/info.js
  /_info:
    get:
      tags:
        - Service information
      description: Gets information about the service
      produces:
        - application/json
      x-amples:
        - title: retrieve service info
          request: {}
          response:
            status: 200
            headers:
              content-type: application/json
            body:
              name: /.+/
              description: /.+/
              version: /.+/
              home: /.+/
  /_info/name:
    get:
      tags:
        - Service information
        - Service name
      description: Gets the name of the service
      produces:
        - application/json
      x-amples:
        - title: retrieve service name
          request: {}
          response:
            status: 200
            headers:
              content-type: application/json
            body:
              name: /.+/
  /_info/version:
    get:
      tags:
        - Service information
        - Service version
      description: Gets the running version of the service
      produces:
        - application/json
      x-amples:
        - title: retrieve service version
          request: {}
          response:
            status: 200
            headers:
              content-type: application/json
            body:
              version: /.+/
  /_info/home:
    get:
      tags:
        - Service information
        - Service homepage
      description: Redirects to the home page
      x-amples:
        - title: redirect to the home page
          request: {}
          response:
            status: 301

  # from routes/kartozoa.js
  /{src}/{z}/{x}/{y}.{format}:
    get:
      description: Returns a tile based on source, zoom, coordinates, and format. Possible values for the various parameters depend on the Kartotherian sources configuration (see https://github.com/kartotherian/kartotherian-core#sources)
      produces:
        - application/octet-stream
        - application/json
        - image/png
        - image/jpeg
        - image/svg+xml
        - text/html
    parameters:
      - name: src
        in: path
        description: Tile source name
        type: string
      - name: z
        in: path
        description: Zoom level of the tile
        type: integer
      - name: x
        in: path
        description: X coordinate of the tile
        type: integer
      - name: 'y'
        in: path
        description: Y coordinate of the tile
        type: integer
      - name: format
        in: path
        description: File format of the tile
        type: string
  /{src}/{z}/{x}/{y}@{scale}x.{format}:
    get:
      description: Returns a tile based on source, zoom, coordinates, scale, and format. Possible values for the various parameters depend on the Kartotherian sources configuration (see https://github.com/kartotherian/kartotherian-core#sources)
      produces:
        - application/octet-stream
        - application/json
        - image/png
        - image/jpeg
        - image/svg+xml
        - text/html
    parameters:
      - name: src
        in: path
        description: Tile source name
        type: string
      - name: z
        in: path
        description: Zoom level of the tile
        type: integer
      - name: x
        in: path
        description: X coordinate of the tile
        type: integer
      - name: 'y'
        in: path
        description: Y coordinate of the tile
        type: integer
      - name: scale
        in: path
        description: Scale for rendering larger images to high resolution screens
        type: number
      - name: format
        in: path
        description: File format of the tile
        type: string
  /{src}/{info}.json:
    get:
      description: Returns information on a given source
      produces:
        - application/json
    parameters:
      - name: src
        in: path
        description: Tile source name (see https://github.com/kartotherian/kartotherian-core#sources)
        type: string
      - name: info
        in: path
        description: Either 'pbfinfo' for a pbf source or 'info' for an image source
        type: string
  /preview:
    get:
      description: Returns a preview slippy map of the server's tiles
      produces:
        - text/html
